- pluginName: KriyaExt
  className: org.mvss.karta.samples.plugins.KriyaExtPlugin

- pluginName: RandomTestDataSource
  className: org.mvss.karta.samples.plugins.RandomTestDataSource

- pluginName: CSVTestDataSourcePlugin
  className: org.mvss.karta.samples.plugins.CSVTestDataSourcePlugin
