---
name: UIAutomation
description: This is a sample YAML format feature file testing web UI automation.

testScenarios:
  - name: UIScenario1
    executionSteps:
      - identifier: When the UI button "1" is pressed
      - identifier: And the UI button "+" is pressed
      - identifier: And the UI button "2" is pressed
      - identifier: And the UI button "=" is pressed
      - identifier: And the calculator should display "3"
