server.port=18080

security.require-ssl=true

# The format used for the keystore 
server.ssl.key-store-type=PKCS12
# The path to the keystore containing the certificate
server.ssl.key-store=keyStore.p12
# The password used to generate the certificate
server.ssl.key-store-password=changeit
# The alias mapped to the certificate
server.ssl.key-alias=karta

#JPA properties
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:./karta;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.url=jdbc:h2:file:./KartaDashboard
#jdbc:h2:./KartaDashboard;DB_CLOSE_ON_EXIT=TRUE

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

spring.datasource.username=karta
spring.datasource.password=karta@123

spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1
