# The Karta runtime configuration file. Refer to the comments on each field.
### Environment and java system properties passed are expanded for the template variables with syntax ${varName} example: ${KARTA_HOME}

### List of directories where plugin jars are to be loaded from
pluginsDirectories:
  - "${KARTA_HOME}/plugins/"
  - "."
### The list of plugin names which are to be enabled. Only enabled plugins are intialized and closed
enabledPlugins:
  - Kriya
  - DataFilesTestDataSource
  - ObjectGenTestDataSource
  - LoggingTestEventListener
  - BeanShellStepRunner
  - JythonStepRunner
  - Gherkin
  - CSVTestDataSourcePlugin
  - GroovyStepRunner
  - XlangStepRunner

### The default feature source parser plugin name
defaultFeatureSourceParsers:
  - Kriya
  - Gherkin
### The default step runner plugin name
defaultStepRunners:
  - Kriya
  - BeanShellStepRunner
  - JythonStepRunner
  - GroovyStepRunner
  - XlangStepRunner
### The default list of test data source plugin name
defaultTestDataSources:
  - DataFilesTestDataSource

### The list of property files to load properties from (YAML/JSON/XML based on file extention)
propertyFiles:
  - KartaProperties.yaml
  - KartaPluginProperties.yaml
  - KartaTestProperties

### The SSL connection properties for Karta if enabling SSL for node communication
sslProperties:
  trustStoreType: jks
  trustStore: "${KARTA_HOME}/bin/trustStore.jks"
  trustStorePassword: changeit
  keyStoreType: pkcs12
  keyStore: "${KARTA_HOME}/bin/keyStore.p12"
  keyStorePassword: changeit

### The name of this node
nodeName: local

### List of nodes/minions
### nodes:
###   - name: Node1
###     host: localhost
###     port: 17171
###     enableSSL: true
###     nodeType: RMI
###     minion: true

###   - name: Node2
###     host: localhost
###     port: 18080
###     enableSSL: true
###     nodeType: REST
###     minion: true
nodes: [ ]

### If minions are to be enabled
minionsEnabled: true

### Thread group name map to the number of threads to use to run tests with for the thread group. __default__ is the name of the default thread group
threadGroups:
  __default__: 1

### The packages to look for configuration objects like Beans
configurationScanPackages: [ ]

### The properties for various property groups.
### Each group is a property key to value map
properties:
  Karta:
    EventProcessor.numberOfThread: 1
    EventProcessor.maxEventQueueSize: 100
    detailedResults: false
    node.config:
      host: localhost
      port: "17171"
      enableSSL: true

  ### Add your step definition and chaos definition package names here
  Kriya:
    stepDefinitionPackageNames: [ ]
    chaosActionDefinitionPackageNames: [ ]

  # DataFilesTestDataSource:
  #   dataPath:
  #     - testdata

  DumpToFileTestEventListener:
    fileName: KartaEventsRawDump.bin

  HTMLReportTestEventListener:
    runReportsBaseFolderName: reports

  RabbitMQTestEventListener:
    queueName: KartaEvents
    userName: guest
    password: guest
    virtualHost: "/"
    hostName: localhost
    portNumber: 5672
