- pluginName: Kriya
  className: org.mvss.karta.framework.runtime.impl.KriyaPlugin

- pluginName: DataFilesTestDataSource
  className: org.mvss.karta.framework.runtime.impl.DataFilesTestDataSource

- pluginName: ObjectGenTestDataSource
  className: org.mvss.karta.framework.runtime.impl.ObjectGenTestDataSource

- pluginName: LoggingTestEventListener
  className: org.mvss.karta.framework.runtime.impl.LoggingTestEventListener

- pluginName: DumpToFileTestEventListener
  className: org.mvss.karta.framework.runtime.impl.DumpToFileTestEventListener

- pluginName: RabbitMQTestEventListener
  className: org.mvss.karta.framework.runtime.impl.RabbitMQTestEventListener

- pluginName: HTMLReportTestEventListener
  className: org.mvss.karta.framework.runtime.impl.HTMLReportTestEventListener
