pluginsDirectories:
  - "${KARTA_HOME}/plugins/"
  - "."
enabledPlugins:
  - Kriya
  - DataFilesTestDataSource
  - ObjectGenTestDataSource
  - RandomTestDataSource
  - LoggingTestEventListener
  - DumpToFileTestEventListener
  #- RabbitMQTestEventListener
  - GherkinPlugin
  - CSVTestDataSourcePlugin
  - HTMLReportTestEventListener

defaultFeatureSourceParserPlugin: Kriya
defaultStepRunnerPlugin: Kriya
defaultTestDataSourcePlugins:
  - DataFilesTestDataSource
  - RandomTestDataSource

propertyFiles:
  - SampleRunProperties.yaml
  - SampleRunProperties2.yaml

sslProperties:
  trustStoreType: jks
  trustStore: "${KARTA_HOME}/bin/trustStore.jks"
  trustStorePassword: changeit
  keyStoreType: pkcs12
  keyStore: "${KARTA_HOME}/bin/keyStore.p12"
  keyStorePassword: changeit

nodeName: local

nodes:
  - name: Node1
    host: localhost
    port: 18080
    enableSSL: true
    nodeType: REST
    minion: true

  - name: Node2
    host: localhost
    port: 18080
    enableSSL: true
    nodeType: REST
    minion: true

minionsEnabled: true

threadGroups:
  __default__: 1
  calculator: 5
  calcChaos: 1

configurationScanPackages:
  - org.mvss.karta.samples.config

testCatalogFragmentFiles:
  - SampleTestCatalogFragment.yaml

properties:
  Karta:
    EventProcessor.numberOfThread: 10
    EventProcessor.maxEventQueueSize: 100
    node.config:
      host: localhost
      port: 17171
      enableSSL: true

  Kriya:
    stepDefinitionPackageNames:
      - org.mvss.karta.samples.stepdefinitions
    chaosActionDefinitionPackageNames:
      - org.mvss.karta.samples.chaosdefinitions

  DumpToFileTestEventListener:
    fileName: KartaEventsRawDump.bin

  RabbitMQTestEventListener:
    queueName: KartaEvents
    userName: guest
    password: guest
    virtualHost: "/"
    hostName: localhost
    portNumber: 5672

  DataFilesTestDataSource:
    dataPath:
      - dataFile1.yaml
      - testDataFolder

  HTMLReportTestEventListener:
    runReportsBaseFolderName: sampleReports

  ObjectGenTestDataSource:
    objectRuleMap:
      employee:
        ruleType: OBJECT_RULE
        fieldGenRules:
          - fieldName: employeeId
            ruleType: STRING_RANGE
            range:
              min: 6
              max: 6
          - fieldName: name
            ruleType: STRING_RANGE
            range:
              min: 5
              max: 12
          - fieldName: gender
            ruleType: MUTEX_OBJECT_RULE_VALUE
            fieldGenRules:
              - ruleType: VALUES
                probability: 0.9
                values:
                  - FEMALE
                  - MALE
              - ruleType: VALUES
                probability: 0.1
                values:
                  - TRANSGENDER
          - fieldName: married
            ruleType: BOOLEAN
          - fieldName: role
            ruleType: MUTEX_OBJECT_RULE_VALUE
            fieldGenRules:
              - ruleType: VALUES
                probability: 0.9
                values:
                  - ENGINEER
              - ruleType: VALUES
                probability: 0.09
                values:
                  - MANAGER
              - ruleType: VALUES
                probability: 0.01
                values:
                  - EXECUTIVE
          - fieldName: salary
            ruleType: INTEGER_RANGE
            range:
              min: 100000
              max: 200000
          - fieldName: address
            ruleType: STRING_RANGE
            range:
              min: 20
              max: 20
