pluginConfigurations:
  - pluginName: KriyaExt
    className: org.mvss.karta.samples.plugins.KriyaExtPlugin
    jarFile: samples.jar

  - pluginName: RandomTestDataSource
    className: org.mvss.karta.samples.plugins.RandomTestDataSource
    jarFile: samples.jar

enabledPlugins:
  - HTMLReportTestEventListener
  - ObjectGenTestDataSource
  - RandomTestDataSource
  - DumpToFileTestEventListener
  - CSVTestDataSourcePlugin

propertyFiles:
  - SampleRunProperties.yaml
  - SampleRunProperties2.yaml
  - SampleRunProperties3.properties
  - WebAutomationProperties.yaml
  - BeanShellStepRunnerProperties.yaml
  - JythonStepRunnerProperties.yaml
  - GroovyStepRunnerProperties.yaml

nodes:
  - name: Node1
    host: localhost
    port: 18080
    enableSSL: true
    nodeType: REST
    minion: true

  - name: Node2
    host: localhost
    port: 18080
    enableSSL: true
    nodeType: REST
    minion: true

threadGroups:
  calculator: 5
  calcChaos: 1

configurationScanPackages:
  - org.mvss.karta.samples

testCatalogFragmentFiles:
  - SampleTestCatalogFragment.yaml

properties:
  Karta:
    detailedResults: true
    EventProcessor.numberOfThread: 10

  Kriya:
    stepDefinitionPackageNames:
      - org.mvss.karta.samples

  DataFilesTestDataSource:
    dataPath:
      - dataFile1.yaml
      - testDataFolder

  HTMLReportTestEventListener:
    runReportsBaseFolderName: sampleReports

  ObjectGenTestDataSource:
    objectRuleMap:
      employee:
        ruleType: OBJECT_RULE
        fieldGenRules:
          - fieldName: employeeId
            ruleType: STRING_RANGE
            range:
              min: 6
              max: 6
          - fieldName: name
            ruleType: STRING_RANGE
            range:
              min: 5
              max: 12
          - fieldName: gender
            ruleType: MUTEX_OBJECT_RULE_VALUE
            fieldGenRules:
              - ruleType: VALUES
                probability: 0.9
                values:
                  - FEMALE
                  - MALE
              - ruleType: VALUES
                probability: 0.1
                values:
                  - TRANSGENDER
          - fieldName: married
            ruleType: BOOLEAN
          - fieldName: role
            ruleType: MUTEX_OBJECT_RULE_VALUE
            fieldGenRules:
              - ruleType: VALUES
                probability: 0.9
                values:
                  - ENGINEER
              - ruleType: VALUES
                probability: 0.09
                values:
                  - MANAGER
              - ruleType: VALUES
                probability: 0.01
                values:
                  - EXECUTIVE
          - fieldName: salary
            ruleType: INTEGER_RANGE
            range:
              min: 100000
              max: 200000
          - fieldName: address
            ruleType: STRING_RANGE
            range:
              min: 20
              max: 20
