pluginsDirectories:
  - "${KARTA_HOME}/plugins/"
  - "."
enabledPlugins:
  - Kriya
  - DataFilesTestDataSource
  - LoggingTestEventListener

defaultFeatureSourceParserPlugin: Kriya
defaultStepRunnerPlugin: Kriya
defaultTestDataSourcePlugins:
  - DataFilesTestDataSource

propertyFiles:
  - KartaRuntimeProperties.yaml

sslProperties:
  trustStoreType: jks
  trustStore: "${KARTA_HOME}/bin/trustStore.jks"
  trustStorePassword: changeit
  keyStoreType: pkcs12
  keyStore: "${KARTA_HOME}/bin/keyStore.p12"
  keyStorePassword: changeit

nodeName: local

nodes: {}
