pluginsDirectory: "."
enabledPlugins:
  - Kriya
  - KriyaExt
  - DataFilesTestDataSource
  - ObjectGenTestDataSource
  - RandomTestDataSource
  - LoggingTestEventListener
  - DumpToFileTestEventListener
  #- RabbitMQTestEventListener
  - CSVTestDataSourcePlugin

defaultFeatureSourceParserPlugin: Kriya
defaultStepRunnerPlugin: Kriya
defaultTestDataSourcePlugins:
  - DataFilesTestDataSource
  - RandomTestDataSource

propertyFiles:
  - KartaRuntimeProperties.yaml
  - SampleRunProperties.yaml
  - SampleRunProperties2.yaml

testRepositorydirectories:
  - "."

testCatalogFiles:
  - "../repository/KartaTestCatalog.yaml"

sslProperties:
  trustStoreType: jks
  trustStore: "../bin/trustStore.jks"
  trustStorePassword: changeit
  keyStoreType: pkcs12
  keyStore: "../bin/keyStore.p12"
  keyStorePassword: changeit

nodeName: local

nodes:
  Node1:
    host: localhost
    port: 17171
    enableSSL: true
  Node2:
    host: localhost
    port: 17171
    enableSSL: true
