---
pluginConfigs:
  - pluginName: Yerkin
    pluginTypes:
      - org.mvss.karta.framework.runtime.interfaces.FeatureSourceParser
      - org.mvss.karta.framework.runtime.interfaces.StepRunner
      - org.mvss.karta.framework.runtime.interfaces.TestDataSource
    className: org.mvss.karta.framework.runtime.impl.YerkinPlugin

  - pluginName: KartaObjectGenTestDataSource
    pluginTypes:
      - org.mvss.karta.framework.runtime.interfaces.TestDataSource
    className: org.mvss.karta.framework.runtime.impl.ObjectGenTestDataSource

  - pluginName: KartaDefaultTestEventListener
    pluginTypes:
      - org.mvss.karta.framework.runtime.interfaces.TestEventListener
    className: org.mvss.karta.framework.runtime.impl.DefaultTestEventListener

  - pluginName: KartaDumpToFileTestEventListener
    pluginTypes:
      - org.mvss.karta.framework.runtime.interfaces.TestEventListener
    className: org.mvss.karta.framework.runtime.impl.DumpToFileTestEventListener

  - pluginName: KartaRabbitMQTestEventListener
    pluginTypes:
      - org.mvss.karta.framework.runtime.interfaces.TestEventListener
    className: org.mvss.karta.framework.runtime.impl.RabbitMQTestEventListener

pluginsDirectory: "."
