name: Docker Image CI

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      imageName:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Number of docker image to create"
        # Default value if no value is explicitly provided
        default: "karta:0.1.3"
        # Input has to be provided for the workflow to run
        required: false

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package -DskipTests -T 4 --file pom.xml
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.event.inputs.imageName }}
